### ISSUE TITLE
Page d'accueil vide

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#1]
La page d'accueil est vide...

**Comment by MBourdim** [comment]
Bonjour monsieur,
La page d'accueil n'est pas vide c'est Mathieu qui c'est occupé de la faire
normalement.

Cordialement

Mathias Bourdim

**Comment by jframiara** [comment]
Comme cela c'est plus clair ?
![copieecran](https://user-images.githubusercontent.com/23612833/73329368-c30ca900-425d-11ea-935f-ec85d93c71c9.jpg)

**Comment by MBourdim** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,
Après analyse du problème nous avons combler la page blanche avec le code correspondant vous le retrouverez dans le git : index.php

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
OK, c'est bon
