### ISSUE TITLE
usertype à NULL

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#11]
Quand on s'inscrit, le usertype est 
![image05](https://user-images.githubusercontent.com/23612833/76897717-8ab83d00-6894-11ea-8d9a-4d89a7215636.jpg)
à NULL

**Comment by MBourdim** [comment]
Bonjour Monsieur ,

Problème résolu 

Cordialement 

Equipe m2l

**Comment by jframiara** [comment]
OK, c'est bon.
