### ISSUE TITLE
Pas de create database

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#12]
Dans le script sql "m2l.sql", il n'y a pas de "create database". Il reste aussi un autre script "BDD.txt". Lequel choisir ???

**Comment by MatthieuBDG** [comment]
Bonjour Monsieur ,

Problème résolu

Cordialement

Equipe m2l

**Comment by jframiara** [comment]
Il y a deux fichiers dans /db. Lequel choisir ?
![img06](https://user-images.githubusercontent.com/23612833/77526026-3875ae00-6e8a-11ea-9ab2-b5244388ac29.jpg)

**Comment by MBourdim** [comment]
Bonjour monsieur 

Erreur avec github le problème est résolu 

Cordialement 

Equipe m2l

**Comment by jframiara** [comment]
OK, c'est bon.
