### ISSUE TITLE
Pas de FK

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#14]
Le schéma de la base de données ne contient aucune clé étrangère.
![img07](https://user-images.githubusercontent.com/23612833/77526310-aa4df780-6e8a-11ea-878b-8be34b32b863.jpg)

**Comment by AxelGGNT** [comment]
Bonjour, 
Erreur dans la base de données corrigée.

**Comment by jframiara** [comment]
OK, c'est bon.
