### ISSUE TITLE
Icônes en trop 

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#16]
Quand on est utilisateur, on voit les icônes des admin. même si on ne peut pas les utiliser. Il faudrait les enlever.
![img08](https://user-images.githubusercontent.com/23612833/77527254-1e3ccf80-6e8c-11ea-9817-c4a1a400dcc2.jpg)

**Comment by AxelGGNT** [comment]
Bonjour, 
Erreur dans la gestion du tableau corrigée.

**Comment by jframiara** [comment]
OK, c'est bon.

**Comment by jframiara** [comment]
OK, c'est bon.
