### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#2]
La documentation du projet est à faire

**Comment by MBourdim** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,  
Après analyse du problème nous avons mis en place la documentation du projet que vous pouvez retrouvez sur le git : README.md .

Cordialement 

Equipe M2L

**Comment by jframiara** [comment]
OK mais il faudrait d'autres documents comme le MLD ou les spécifications fournies (fichier PDF). Vous pouvez faire des liens vers GDrive

**Comment by jframiara** [comment]
Toujours pas fait !

**Comment by jframiara** [comment]
Toujours pas fait. Il manque en plus un manuel d'installation (qu'on peut ajouter dans le [README.md](https://github.com/MBourdim/M2L/blob/master/README.md)).

**Comment by AxelGGNT** [comment]
Documentation intégrée au dossier M2L et readme.md finalisé (ajout du manuel d'installation).

**Comment by jframiara** [comment]
OK, c'est bon.
