### ISSUE TITLE
Page "liste des questions" incomplète

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#3]
La page "liste des questions" est incomplète. 
- Le menu n'est pas terminé et incohérent avec la page d'accueil. 
- Le tableau n'est pas terminé (il manque des bordures).
- il manque les liens pour répondre et supprimer les questions

**Comment by MatthieuBDG** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L.
Après analyse du problème nous avons corrigés le problème lié au menu de la page d'accueil .
La page s'affiche correctement.
Egalement nous avons corrigé le soucis du tableau et des liens pour répondre et supprimer les questions.

Merci de suivre le projet nous suivons vos retour .

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
La liste des questions ne correspond pas à ce qui est dans la base...

**Comment by MBourdim** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,
Nous avons régler le problème la page list.php affiche les questions de la base de donnée .
Merci de suivre le projet nous suivons vos retour .

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
La liste des questions est accessible même sans être connecté. Elle est vide certe mais on la voit.

**Comment by jframiara** [comment]
OK, c'est bon.
