### ISSUE TITLE
Page "répondre" vide

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#4]
La page "répondre" est vide. Il faudrait au minimum la partie commune (entête, menu,...) et le formulaire.

**Comment by MathieuARMD** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,
Après analyse du problème nous avons modifié la page "répondre" nommée "edit.php" elle dispose d'une entête, d'un menu et du formulaire pour l'instant non fonctionnel.

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
La page ne fonctionne pas : la question est vide et la réponse n'est pas enregistrée !
Quand on clique sur le bouton, on va à "localhost/sql" ???

**Comment by jframiara** [comment]
OK, c'est bon.
