### ISSUE TITLE
Erreur PHP sur la page  "supprimer"

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#5]
La page "supprimer" contient un message d'erreur PHP. 
 Uncaught Error: Call to undefined function mysql_connect()

**Comment by MBourdim** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,
Après analyse du problème nous avons corrigés le problème lié a la connexion à la base de donnée .
La page affiche maintenant que le message a bien été supprimer .
Merci de suivre le projet nous suivons vos retour .

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
Le message n'est pas supprimé !

**Comment by jframiara** [comment]
OK, c'est bon.
