### ISSUE TITLE
Pas de connexion ni d'inscription

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#6]
On ne peut pas s'inscrire (rien dans la base)  et la liste des questions est accessible même sans connexion.

**Comment by MBourdim** [comment]
Bonjour monsieur,
Merci pour votre remarque concernant le projet M2L,
Après analyse du problème nous avons corrigés le problème lié a la connexion et l'inscription à la base de donnée .
Merci de suivre le projet nous suivons vos retour .

Cordialement

Equipe M2L

**Comment by jframiara** [comment]
OK, on peut s'inscrire.
