### ISSUE TITLE
Impossible de se connecter

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#7]
Après inscription, on ne peut pas se connecter. On obtient une erreur "Undefined variable: connect in C:\xampp\htdocs\projets\PPE2\rendu_20200317\Groupe_C\M2L-master\login.php on line 11".
![image04](https://user-images.githubusercontent.com/23612833/76897045-4aa48a80-6893-11ea-8127-138590e020cf.jpg)

**Comment by MatthieuBDG** [comment]
Bonjour Monsieur ,

Problème résolu

Cordialement

Equipe m2l

**Comment by jframiara** [comment]
OK, c'est bon.

**Comment by jframiara** [comment]
OK, c'est bon.
