### ISSUE TITLE
Onglet de la liste des questions

### ISSUE THREAD

**Issue by jframiara** [MBourdim/M2L#8]
Dans l'onglet de la liste des questions, on voit "répondre". Qu'est ce que cela a à voir avec une liste ?

**Comment by MathieuARMD** [comment]
Bonjour Monsieur ,

Problème résolu

Cordialement

Equipe m2l

**Comment by AxelGGNT** [comment]
Bonsoir, 
Le problème est résolu.
Axel GAGNANT

**Comment by jframiara** [comment]
OK, c'est bon.
